# EXERCICI 1

### funció que d'una array 1-D faci un resum estadístic bàsic, del contrari doni missatge "error"

In [1]:
import numpy as np
from numpy import random
from scipy import stats

a = random.randint(1, 100, size=(7), dtype='i')
print(a)
print(a.ndim)

if a.ndim > 1:
    print("error")
    
else:
    b = np.mean(a) # mitja
    c = np.std(a) # desviacio estandard
    d = np.median(a) # mitjana
    e = np.var(a) # variança
    f = stats.mode(a) # moda
    g = np.cov(a) # covariança
    
#funcio resum estadistic

def funcio(estadistica):
    for x in estadistica:
        print(x)
        
valors = ["mitja", b, 
          "desviacio", c,
          "mitjana", d,
          "variança", e,
          "moda", f,
          "covariança", g]

funcio(valors)

[24 24 72 41 61 85 15]
1
mitja
46.0
desviacio
25.002856979610492
mitjana
41.0
variança
625.1428571428571
moda
ModeResult(mode=array([24], dtype=int32), count=array([2]))
covariança
729.3333333333333


# EXERCICI 2

### crear funció que generi un quadrat NxN de nombres aleatoris entre 0 i 100.

In [2]:
nn = random.randint(0, 100, (7, 7))
print(nn)
nn.shape

[[27 19 16 34 33 62 77]
 [28 20 10 84 53 98 15]
 [26 63 15  2  3 86 80]
 [91 50 60 81 57 58 72]
 [15 15 82 79  3 13 21]
 [54 12 77 80 10 74 85]
 [29  9 89 52 27 13 27]]


(7, 7)

# EXERCICI 3

### crear funció que donada una taula de 2 dimensions (NxM), calculi els totals per fila i els totals per columna.

In [3]:
nm = random.randint(0, 100, (2, 5))
print(nm)

#suma totals per fila
total_files = np.sum(nm[:], axis=1)
print (total_files)

#suma totals per columna
total_columnes = np.sum(nm[:], axis=0)
print (total_columnes)

[[67 98 65 80 92]
 [69 92  5 81 83]]
[402 330]
[136 190  70 161 175]


# EXERCICI 4

### implementar manualment funció que calculi el coeficient de correlació, informar usos i interpretació.

In [7]:
# Coeficient de correlació lineal (r): relació de linealitat o proporcionalitat entre dues variables.
# -1 =< r =< +1 (r(+) correlació directa --- r = 0 no existeix correlació --- r(-) correlació inversa) 

cor = random.randint(0, 100, (2, 3))
np.corrcoef(cor) # crea array de correlació
print(cor)

m1= np.mean(cor[0]) #mitja
m2 = np.mean(cor[1])

d1 = np.std(cor[0]) #desviació
d2 = np.std(cor[1])

r= (1/3-1)*((((cor[0, 0])-m1)/d1)*(((cor[1, 0])-m2)/d2)+(((cor[0, 1])-m1)/d1)*(((cor[1, 1])-m2)/d2)+(((cor[0, 2])-m1)/d1)*(((cor[1, 2])-m2)/d2))
print (r)

coeficient_correlacio = np.corrcoef(cor[:, 0], cor[:, 1])
print (coeficient_correlacio)

[[ 4 54 33]
 [45 77  0]]
-0.6562469845168207
[[1. 1.]
 [1. 1.]]
